export const buttonList = [
    {
    	data: "AC",
        id: "clear",
        input: "clear",
        color: "blue",
    },
    {
    	data: "-/+",
        id: "negative",
        input: "negative",
        color: "blue",
    },
    {
    	data: "%",
        id: "percent",
        input: "%",
        color: "blue",
    },
    {
    	data: "/",
        id: "divide",
        input: "/",
        color: "blue",
    },
    {
    	data: "7",
        id: "seven",
        input: "7",
        color: "gray",
    },
    {
    	data: "8",
        id: "eight",
        input: "8",
        color: "gray",
    },
    {
    	data: "9",
        id: "nine",
        input: "9",
        color: "gray",
    },
    {
    	data: "*",
        id: "multiply",
        input: "*",
        color: "blue",
    },
    {
    	data: "4",
        id: "four",
        input: "4",
        color: "gray",
    },
    {
    	data: "5",
        id: "five",
        input: "5",
        color: "gray",
    },
    {
    	data: "6",
        id: "six",
        input: "6",
        color: "gray",
    },
    {
    	data: "-",
        id: "subtract",
        input: "-",
        color: "blue",
    },
    {
    	data: "1",
        id: "one",
        input: "1",
        color: "gray",
    },
    {
    	data: "2",
        id: "two",
        input: "2",
        color: "gray",
    },
    {
    	data: "3",
        id: "three",
        input: "3",
        color: "gray",
    },
    {
    	data: "+",
        id: "add",
        input: "+",
        color: "blue",
    },
    {
    	data: "0",
        id: "zero",
        input: "0",
        color: "blue",
    },
    {
    	data: ".",
        id: "decimal",
        input: ".",
        color: "blue",
    },
    {
    	data: "=",
        id: "equals",
        input: "=",
        color: "red",
    },
];
